services:
  - type: web
    name: math-tools
    env: python
    plan: free  
    branch: main
    rootDir: backend 
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app 
    envVars:
      - key: FLASK_ENV
        value: production
